### ISSUE TITLE
Can't add negatives to a choose or a sequence

### ISSUE THREAD

**Issue by WaltWh** [chaosprint/glicol#103]
same goes for multiplying.

```
pos[246], line[9], col[25], positives[number, reference], negatives[]
Error at line 9
~test: choose 80 >> add  -20
________________________^^^ expecting number || reference 
```

Adding or multiplying by a positive number works just fine, and adding a negative to the output of e.g. a `sin` doesn't seem to have problems - I'm sure it's not *just* `seq` and `choose` but those are the only ones I've found.

**Comment by chaosprint** [comment]
Thanks for reporting this bug.
It's due to the parser error and it's fixed now.
Now you can do:
```
out: speed 16 >> seq ~a >> sawsynth 0.01 0.1
~a: choose 60 >> add -12
```
The output of `seq` is slightly different as the midi notes are converted into signals there, e.g. 60 becomes 1.0.
