### ISSUE TITLE
`delayms` emits mono signal but it should upmix to stereo

### ISSUE THREAD

**Issue by orottier** [chaosprint/glicol#107]
In the following snippet, the feedback signal is only sent to a single channel, but it should be added in stereo
```
~pingvol: imp 0.33 >> envperc 0.001 0.1
~ping: sin ~freq >> mul ~pingvol
~delay: ~ping >> add ~delay >> mul 0.5 >> delayms 300
~freq: sin 2 >> add 1 >> mul 200 >> add 800

main: mix ~ping ~delay
```

**Comment by chaosprint** [comment]
It is fixed on [`v0.12.9`](https://glicol.org) although it is a hard-coded stereo. I will test multi-chan stuff in the future.
