### ISSUE TITLE
Panic when reconnecting balance node

### ISSUE THREAD

**Issue by FalkorX** [chaosprint/glicol#108]
When I start playing this
```
~t1: sin 440
~t2: sin 330
~t3: sin 550
o: balance ~t1 ~t2
```
and then reconnect the balance node like this `o: balance ~t1 ~t3`, it panics. I played around with it a little, and in many cases where I try to reconnect a balance node that was previously connected to something else, a similar panic happens.

Backtrace:
```
0080ceae:0x10a5fa Uncaught RuntimeError: unreachable
    at rust_panic (0080ceae:0x10a5fa)
    at _ZN3std9panicking20rust_panic_with_hook17h12b2f0179ff84c92E (0080ceae:0xb7cdb)
    at _ZN3std9panicking19begin_panic_handler28_$u7b$$u7b$closure$u7d$$u7d$17h5a69bb4aef967681E (0080ceae:0x10a829)
    at _ZN3std10sys_common9backtrace26__rust_end_short_backtrace17h1cfd7c1c16d2a171E (0080ceae:0x10a806)
    at rust_begin_unwind (0080ceae:0x40138)
    at _ZN4core9panicking9panic_fmt17hf0d93ec1ac504cf9E (0080ceae:0x9749)
    at _ZN4core9panicking18panic_bounds_check17hebe834b116d5d452E (0080ceae:0x9c2c)
    at _ZN81_$LT$alloc..vec..Vec$LT$T$C$A$GT$$u20$as$u20$core..ops..index..Index$LT$I$GT$$GT$5index17h12de798c45eb5c9eE (0080ceae:0x316e9)
    at _ZN98_$LT$glicol_synth..node..effect..balance..Balance$u20$as$u20$glicol_synth..node..Node$LT$_$GT$$GT$7process17ha1ba01cff16dc1f5E (0080ceae:0x36789)
    at _ZN12glicol_synth5graph22Processor$LT$G$C$_$GT$7process17ha9a3cf893de82f10E (0080ceae:0x998d)
$rust_panic @ 0080ceae:0x10a5fa
$_ZN3std9panicking20rust_panic_with_hook17h12b2f0179ff84c92E @ 0080ceae:0xb7cdb
$_ZN3std9panicking19begin_panic_handler28_$u7b$$u7b$closure$u7d$$u7d$17h5a69bb4aef967681E @ 0080ceae:0x10a829
$_ZN3std10sys_common9backtrace26__rust_end_short_backtrace17h1cfd7c1c16d2a171E @ 0080ceae:0x10a806
$rust_begin_unwind @ 0080ceae:0x40138
$_ZN4core9panicking9panic_fmt17hf0d93ec1ac504cf9E @ 0080ceae:0x9749
$_ZN4core9panicking18panic_bounds_check17hebe834b116d5d452E @ 0080ceae:0x9c2c
$_ZN81_$LT$alloc..vec..Vec$LT$T$C$A$GT$$u20$as$u20$core..ops..index..Index$LT$I$GT$$GT$5index17h12de798c45eb5c9eE @ 0080ceae:0x316e9
$_ZN98_$LT$glicol_synth..node..effect..balance..Balance$u20$as$u20$glicol_synth..node..Node$LT$_$GT$$GT$7process17ha1ba01cff16dc1f5E @ 0080ceae:0x36789
$_ZN12glicol_synth5graph22Processor$LT$G$C$_$GT$7process17ha9a3cf893de82f10E @ 0080ceae:0x998d
$process @ 0080ceae:0x591a
process @ 6ff007ee-aff5-454c-aa3d-17b2c4c2bbaa:324
```

**Comment by Freyert** [comment]
did a quick google search and this might be an issue with the `rustup-wasm` runtime https://github.com/rustwasm/wasm-pack/issues/724

I was able to reproduce your bug on the main Glicol site.

When I run the site locally:

```console
cd rs/wasm
chmod +x build.sh
./build.sh
cd ../..
cd js
npm i
npm run dev
```

The editor gives you a start/stop button. stop causes the engine to clear, but when I followed your instructions and hit run without a stop it caused the panic.

Going to try following some of the directions here https://rustwasm.github.io/book/game-of-life/debugging.html

**Comment by FalkorX** [comment]
Hey @Freyert, sorry, saw your comment just now. I myself just stumbled across this when playing around with it on the website. I'm not really a Rust expert, it just so happens that the website conveniently outputs the stack trace in the browser console when a panic happens :)

**Comment by chaosprint** [comment]
Hi @FalkorX @Freyert, thank you both for looking into this. I think it is caused by the Rust side, which applies to all the panics. `balance` is actually not a complete node for live coding; I made it just to use it as part of the `plate` reverb. But since you post a quite interesting usage here, I will try to solve it. Shouldn't be very difficult.
