### ISSUE TITLE
WASM issue glicol.js

### ISSUE THREAD

**Issue by rudevoltage** [chaosprint/glicol#120]
I'm using vite 3.2.3 and made a JS vanilla project, installed glicol with "npm i glicol", also installed vite-plugin-wasm, "npm i vite-plugin-wasm" and "yarn add -D vite-plugin-wasm", aslo installed "npm i -D vite-plugin-cross-origin-isolation ".

This is my code in main.js:

import './style.css'
import wasm from "vite-plugin-wasm";
import crossOriginIsolation from 'vite-plugin-cross-origin-isolation';
import Glicol from "glicol";

export default defineConfig({
  plugins: [
    wasm(),
    crossOriginIsolation()
   ]
});

this is the error I get when running "npm run dev":

[vite] Internal server error: "ESM integration proposal for Wasm" is not supported currently. Use vite-plugin-wasm or other community plugins to handle this. Alternatively, you can use `.wasm?init` or `.wasm?url`. See https://vitejs.dev/guide/features.html#webassembly for more details.

Not sure what I am doing wrong...

**Comment by chaosprint** [comment]
It seems that the latest version of Vite changed something. As far as I remember it works fine with Vite 3.0.0 but I need to investigate it further.

**Comment by lyricalsoul** [comment]
Having a similar issue. My config looks like this:
```js
export default defineConfig({
  plugins: [crossOriginIsolation(), wasm(), svelte()]
})
```
This is the error I get with it:
```js
[ERROR] Could not resolve "env"

  vite-plugin-wasm-namespace:/home/lyrical/Projects/rhythmic/node_modules/glicol/glicol_wasm.wasm:43:46:
      43 │ import { now as __vite__wasmImport_0_0 } from "env";
         ╵                                               ~~~~~

  You can mark the path "env" as external to exclude it from the bundle, which will remove this
  error.
```

Marking Glicol as a dependency that shouldn't be optimized (like `vite-plugin-wasm` tells you to do) doesn't fix the issue, but it does stop the dev server from crashing.
```js
Failed to resolve import "env" from "node_modules/glicol/glicol_wasm.wasm". Does the file exist?
11:15:47 AM [vite] Internal server error: Failed to resolve import "env" from "node_modules/glicol/glicol_wasm.wasm". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/lyrical/Projects/rhythmic/node_modules/glicol/glicol_wasm.wasm:5:48
  3  |  import __vite__initWasm from "/__vite-plugin-wasm-helper"
  4  |  
  5  |  import { now as __vite__wasmImport_0_0 } from "env";
     |                                                 ^
  6  |  const __vite__wasmModule = await __vite__initWasm({ "env": { now: __vite__wasmImport_0_0 } }, __vite__wasmUrl);
  7  |  export const memory = __vite__wasmModule.memory;
      at formatError (file:///home/lyrical/Projects/rhythmic/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:39975:46)
      at TransformContext.error (file:///home/lyrical/Projects/rhythmic/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:39971:19)
      at normalizeUrl (file:///home/lyrical/Projects/rhythmic/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36839:33)
      at async TransformContext.transform (file:///home/lyrical/Projects/rhythmic/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36972:47)
      at async Object.transform (file:///home/lyrical/Projects/rhythmic/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:40228:30)
      at async loadAndTransform (file:///home/lyrical/Projects/rhythmic/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36615:29)
```

@chaosprint, what version of `vite-plugin-wasm` were you using? feels like an issue with it, not Glicol...

**Comment by rudevoltage** [comment]
I am now using vite 2.9.5 and it works like a charm.

**Comment by Nek** [comment]
Hey. I have the same problem. Sadly, I can't downgrade to vite 2.9.5 because of some other libraries I use.
Have somebody found a solution?

**Comment by chaosprint** [comment]
> Having a similar issue. My config looks like this:
> 
> ```js
> export default defineConfig({
>   plugins: [crossOriginIsolation(), wasm(), svelte()]
> })
> ```
> 
> This is the error I get with it:
> 
> ```js
> [ERROR] Could not resolve "env"
> 
>   vite-plugin-wasm-namespace:/home/lyrical/Projects/rhythmic/node_modules/glicol/glicol_wasm.wasm:43:46:
>       43 │ import { now as __vite__wasmImport_0_0 } from "env";
>          ╵                                               ~~~~~
> 
>   You can mark the path "env" as external to exclude it from the bundle, which will remove this
>   error.
> ```
> 
> Marking Glicol as a dependency that shouldn't be optimized (like `vite-plugin-wasm` tells you to do) doesn't fix the issue, but it does stop the dev server from crashing.
> 
> ```js
> Failed to resolve import "env" from "node_modules/glicol/glicol_wasm.wasm". Does the file exist?
> 11:15:47 AM [vite] Internal server error: Failed to resolve import "env" from "node_modules/glicol/glicol_wasm.wasm". Does the file exist?
>   Plugin: vite:import-analysis
>   File: /home/lyrical/Projects/rhythmic/node_modules/glicol/glicol_wasm.wasm:5:48
>   3  |  import __vite__initWasm from "/__vite-plugin-wasm-helper"
>   4  |  
>   5  |  import { now as __vite__wasmImport_0_0 } from "env";
>      |                                                 ^
>   6  |  const __vite__wasmModule = await __vite__initWasm({ "env": { now: __vite__wasmImport_0_0 } }, __vite__wasmUrl);
>   7  |  export const memory = __vite__wasmModule.memory;
>       at formatError (file:///home/lyrical/Projects/rhythmic/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:39975:46)
>       at TransformContext.error (file:///home/lyrical/Projects/rhythmic/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:39971:19)
>       at normalizeUrl (file:///home/lyrical/Projects/rhythmic/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36839:33)
>       at async TransformContext.transform (file:///home/lyrical/Projects/rhythmic/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36972:47)
>       at async Object.transform (file:///home/lyrical/Projects/rhythmic/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:40228:30)
>       at async loadAndTransform (file:///home/lyrical/Projects/rhythmic/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36615:29)
> ```
> 
> @chaosprint, what version of `vite-plugin-wasm` were you using? feels like an issue with it, not Glicol...
> 
> by the way, these are my dependencies + their version (running on node 19);
> 
> ```json
>   "devDependencies": {
>     "@sveltejs/vite-plugin-svelte": "^1.1.0",
>     "svelte": "^3.52.0",
>     "vite": "^3.2.3",
>     "vite-plugin-cross-origin-isolation": "^0.1.6",
>     "vite-plugin-wasm": "^3.1.0"
>   },
>   "dependencies": {
>     "glicol": "^0.3.8"
>   }
> ```

I don't use any vite plugins for wasm. See the project for example: https://github.com/glicol/glicol-tidal
 I actually use a hack to load it from the node modules but I will do my best to have a look on the new vite in the coming days.

**Comment by chaosprint** [comment]
Vite is now at 4.3... I will probably move JS stuff elsewhere to keep this repo purely Rust.

**Comment by Nek** [comment]
Did you manage to make it work?

**Comment by chaosprint** [comment]
> Did you manage to make it work?

Not yet. I will rewrite the whole repo here and there soon so I plan to do that at the moment.

**Comment by Nek** [comment]
I'm looking forward to seeing a working version. I still want to give it a try. I would make it work and submit it, but I couldn't. It was a bit over my experience.
Thanks for the great project! It's extremely promising for the things I try to build.

**Comment by chaosprint** [comment]
I just updated the package. This should have been fixed. I tested it with Vite 4 + React.

**Comment by Nek** [comment]
I've just tried it with the latest template for solidjs (vite 4.1.1). It works perfectly fine. Thanks!

**Comment by rudevoltage** [comment]
Great! Thanks a lot for your support.
