### ISSUE TITLE
Clarification : DSL and grammar detail for web interface

### ISSUE THREAD

**Issue by chesal** [chaosprint/glicol#122]
Hi,

I am trying to use the [web interface](https://glicol.org/solo), I am using examples listed on [Tour ](https://glicol.org/tour) and [demo](https://glicol.org/demo) but I am still trying to figure out the syntax,rules and keywords to be used.

Is there a list of keywords, rules and a syntax to be respected for the DSL ? I couldn't find any.

Thanks for your inputs.

**Comment by chaosprint** [comment]
it's mentioned in the first two pages in the `tour` that you should open the browser console to see the references and rules.

**Comment by chesal** [comment]
thank you for the answer, but is there a file with all refs and rules ? should I do it manually every-time ?
