### ISSUE TITLE
handleError.js:10 Error: trying to use a non-existent sample.

### ISSUE THREAD

**Issue by jarmitage** [chaosprint/glicol#14]
The sample example at https://glicol.web.app/ doesn't seem to work for me

**Comment by jarmitage** [comment]
Ah... found the "use samples" setting

**Comment by chaosprint** [comment]
@jarmitage  Thanks for the issue.

I have added this hint to the text comment on that example.

You can also add new samples from the console with ```addSample(name, url)```.
