### ISSUE TITLE
Trying to use glicol offline

### ISSUE THREAD

**Issue by asorc** [chaosprint/glicol#159]
Hello,

I have all the files of the cdn repository mirrored on my hard disk. 

I manage to open the index.html with the minimal example, but when I try the hello world  code o1: sin 440, and press the run button, I don't get any sound. 

Any advice on what's not working? 

I would like to use glicol on my browser offline. 

Thank you very much for your attention.

Regards

**Comment by chaosprint** [comment]
to use the js folder offline you need to have pnpm installed.
- `cd js`
- `pnpm i`
- `pnpm dev --open`

however, this will also require the usage of cdn.

to get rid of that completely, you need to comment out this line:

https://github.com/chaosprint/glicol/blob/044fb8d88f61847bc1d20e43e1b9cdcc446ae95c/js/src/glicol.js#L4

I also recommend [glicol-cli ](https://github.com/glicol/glicol-cli) for offline usage

**Comment by asorc** [comment]
I see. Thanks a lot. I have installed rust on Windows 7 following the steps on the link, but I am not sure If Cargo is already installed, or what what are the steps to install Cargo.

On the link It says:

"On Windows, download and run rustup-init.exe. It will start the installation in a console and present the above message on success.

After this, you can use the rustup command to also install beta or nightly channels for Rust and Cargo."

I have run cargo on the command line, and It gives me an error. It tells me to run "rustup default stable". When I run It, the link to download It fails.

**Comment by chaosprint** [comment]
> I see. Thanks a lot. I have installed rust on Windows 7 following the steps on the link, but I am not sure If Cargo is already installed, or what what are the steps to install Cargo.
> 
> On the link It says:
> 
> "On Windows, download and run rustup-init.exe. It will start the installation in a console and present the above message on success.
> 
> After this, you can use the rustup command to also install beta or nightly channels for Rust and Cargo."
> 
> I have run cargo on the command line, and It gives me an error. It tells me to run "rustup default stable". When I run It, the link to download It fails.

not sure how to solve it. Windows 7 may be challenging for development as far as I know.

maybe you can ask here https://users.rust-lang.org/
