### ISSUE TITLE
iOS Safari support?

### ISSUE THREAD

**Issue by tbenst** [chaosprint/glicol#30]
Unfortunately the homepage example plays no audio on iOS safari/firefox. Perhaps this isn’t resolvable due to API limitations

**Comment by chaosprint** [comment]
I assume it has something to do with `SharedArrayBuffer`:
https://caniuse.com/?search=sharedarraybuffer

**Comment by chaosprint** [comment]
won't fix, but added a browser checking in `glicol.js`

**Comment by LiveDuo** [comment]
@chaosprint Seems like the browser checking is broken too. It pops up if you use Google Chrome but if you use Safari on iOS it doesn't (and there's still no sound).

**Comment by chaosprint** [comment]
> 

which iOS version are you using?

**Comment by LiveDuo** [comment]
It's 16.6

**Comment by chaosprint** [comment]
> It's 16.6

Which Apple model is it? I only have an old iPad Mini now. I can get sound but it's slow.

**Comment by LiveDuo** [comment]
I tested it on an iPhone XR and there's no sound at all. I might get to test it on an iPad too. If I do I will let you know.
