### ISSUE TITLE
Add missing help entries for tokens used in tour

### ISSUE THREAD

**Issue by TimonLukas** [chaosprint/glicol#71]
Hey! I just found this project on Reddit, very cool idea and even better website and introduction! Amazing work so far.

While going through the tour and using the VERY helpful ALT+D feature to see details about the tokens, I noticed that in chapter `4. sequencer` there are tokens that don't have any help entries. I have a basic understanding of how digital sound works, but `bd` is an example of a token where I'd definitely need a help entry. In total, I found the following ones to be missing:

- [x] `bd` (`sn`, `hh`)
- [x] `sawsynth` (and consequently `squsynth` and `trisynth`)
- [x] `plate`
- [x] `meta`

Again, as a newbie I think this is a really really helpful feature, once it's complete it will be a perfect introduction!

**Comment by chaosprint** [comment]
Thank you very much for the feedback! I will work on that this week.
