### ISSUE TITLE
Publish as reusable library to NPM

### ISSUE THREAD

**Issue by TimonLukas** [chaosprint/glicol#73]
Hey! Not sure if this is already on your roadmap, but I wanted to look into what it would take to publish this to NPM so it can easily be used in other projects. There's a couple of changes that would have to be made to the JS code, mostly to make it more robust and to improve the way dependencies are loaded and resolved (especially towards the global `window`), but it's not a lot.

If you're interested I could help out on this front, I already have a bit of experience with this kind of thing.

PS: If this is released to NPM, it would also be a good idea to add some type definitions - since your public API is very small it would just be one function right now. However there is actually something REALLY REALLY cool you could do here. Since a couple of versions ago Typescript supports [advanced string types](https://github.com/ghoullier/awesome-template-literal-types), which allow you to do a lot of validation and so on on the type system. I for example have implemented a small ASM parser with it, and it works wonderfully. It shouldn't be too hard to implement a generator for validating GLICOL strings on a type level using your [API file](https://github.com/chaosprint/glicol/blob/main/js/src/glicol-api.json). Could be a fun and useful extension to your project, allowing Typescript users compile-time verification of their GLICOL input!

**Comment by chaosprint** [comment]
Thanks for the suggestion!
Since Glicol relies heavily on AudioWorklet and SharedArrayBuffer, it is very difficult and probably less ergonomic to do that with npm. For example, users need to have `CORS` to enable SharedArrayBuffer (see https://web.dev/cross-origin-isolation-guide).
Yet I am considering building a template for users.

**Comment by TimonLukas** [comment]
I don't think that `AudioWorklet` and `SharedArrayBuffer` would really affect how difficult it would be to use this through NPM, as long as the requirement is documented. To give an example, I have a small browser (idle) game I'm currently working on, which I'm publishing to Github Pages ([repository](https://github.com/TimonLukas/universatorial-extractination)). If I wanted to use your library I could follow [these instructions](https://dev.to/stefnotch/enabling-coop-coep-without-touching-the-server-2d3n) to set the required headers even on Github Pages, and then include your library like every other modern JS library (see for example [the music packages I currently use](https://github.com/TimonLukas/universatorial-extractination/blob/0aec2c392eeebd28fbef473929d0c9ec4f016fde/package.json#L17-L21)).

Personally I wouldn't use a project with manual source management as a dependency in my projects anymore, and this probably goes for a lot of modern devs. But ultimately it's of course your decision!

**Comment by chaosprint** [comment]
> 

You are right. There will always be some solution. I will set this as a relatively long-term goal. For now, I guess to improve the music expression and interaction is the priority.

**Comment by chaosprint** [comment]
supported since v0.12.1
