### ISSUE TITLE
cpu usage on demo has odd behavior

### ISSUE THREAD

**Issue by kapouer** [chaosprint/glicol#93]
I'm seeing CPU usage going 150% using chrome Version 100.0.4896.127 (Build officiel) (64 bits) on debian/bookworm,
after playing a bit with the glicol.org/demo page: edit -> update -> edit -> update -> edit -> update...
Each update rises the CPU usage by several percents, quickly.

Note also: when going to another chrome tab, CPU drops to 13% (and sound still plays nicely),
and when coming back to the Glicol demo tab, CPU bumps again to high values.

**Comment by chaosprint** [comment]
Thanks for the issue! My first guess is that it's related to #89
I will work on that next week.

**Comment by chaosprint** [comment]
@kapouer I think now it should be fine with the new version. Does it work out with your system?
