### ISSUE TITLE
Publish crate for discoverability

### ISSUE THREAD

**Issue by Omicron666** [chaosprint/glicol#94]
Suggestion of publishing glicol crate to help discoverability.
It would also give more metrics.

**Comment by chaosprint** [comment]
Thanks for the suggestion. This is should be on the to-do list. Will try to publish `glicol_synth` first, but I need to organise the code a little bit better, write the comments and docs, etc.

**Comment by chaosprint** [comment]
It's there now and will be updated once a while:
https://crates.io/search?q=glicol
